version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: flex_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=theFlex
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d theFlex"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: flex_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/theFlex?schema=public
      - PORT=3000
      - NODE_ENV=development
      - HOSTAWAY_ACCOUNT_ID=61148 #hardcoding for assessment purposes only
      - HOSTAWAY_API_KEY=f94377ebbbb479490bb3ec364649168dc443dda2e4830facaf5de2e74ccc9152 #hardcoding for assessment purposes only
    depends_on:
      db:
        condition: service_healthy